http://localhost:4000/user?cpf=00000001830

###
POST http://localhost:4000/user/
content-type: application/json

{
    "email": "jcmcf201345@gmail.com",
    "password": "admin1234"
}



###

POST https://udemy-nodejs-backend.sxl9hr.easypanel.host/user/
content-type: application/json

{
    "email": "jcmcf201345@gmail.com",
    "password": "admin1234"
}
